### ISSUE TITLE
Problem with multiple instances support during paste operation

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-clipboard#5] opened 2018-01-30 09:37 UTC
When a node is copied and pasted multiple times, extension behaves weirdly. Furthermore, when two tabs exist, if a node is tried to be copied and pasted in one tab, it pastes to the other tab.

**Comment by metincansiper** [comment] 2018-02-01 04:11
@hasanbalci that is interesting because it works fine in the collaborative editor (that is based on Newt) even with multiple views. You can find it deployed [here](http://35.224.130.169:3000/). If I am not wrong it works well in the demo page of this extension as well (note that there is just one view in demo page, it can at least be said that seems like working fine for one instance). I suppose that it behaves weirdly in Newt. Could it be caused by some changes that are committed after multiple instances/tabs support in Newt or some related libraries (chise.js, sbgnviz.js).

**Comment by hasanbalci** [comment] 2018-02-01 09:02
@metincansiper Thanks, I realized that the problem is about the release of the extension. I think, @kinimesi released the extension without recent updates.

**Closed as completed** 2018-02-01 10:56 UTC
